version: "3"

services:
  aosd:
    image: arisen/arisen:latest
    command: /opt/arisen/bin/aosd.sh --data-dir /opt/arisen/bin/data-dir -e --http-alias=aosd:12618 --http-alias=127.0.0.1:12618 --http-alias=localhost:12618
    hostname: aosd
    ports:
      - 12618:12618
      - 6620:6620
    expose:
      - "12618"
    volumes:
      - aos-data-volume:/opt/arisen/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  awallet:
    image: arisen/arisen:latest
    command: /opt/arisen/bin/awallet --wallet-dir /opt/arisen/bin/data-dir --http-server-address=127.0.0.1:6621 --http-alias=awallet:6621 --http-alias=localhost:6621
    hostname: awallet
    links:
      - aosd
    volumes:
      - awallet-data-volume:/opt/arisen/bin/data-dir
    stop_grace_period: 10m

volumes:
 aos-data-volume:
   external: true
 awallet-data-volume:
   external: true
