version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  aosd:
    build:
      context: .
    image: arisen/arisen
    command: /opt/eosio/bin/aosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=aosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: aosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - aos-data-volume:/opt/eosio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  awallet:
    image: arisen/arisen
    command: /opt/eosio/bin/awallet --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=awallet:8900 --http-alias=localhost:8900
    hostname: awallet
    links:
      - aosd
    volumes:
      - awallet-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m

volumes:
  aos-data-volume:
    external: true
  awallet-data-volume:
    external: true
