version: "3"

services:
  builder:
    build:
      context: builder
    image: arisen/builder

  aosd:
    build:
      context: .
    image: arisen/arisen
    command: /opt/arisen/bin/aosd.sh --data-dir /opt/arisen/bin/data-dir -e --http-alias=aosd:12618 --http-alias=127.0.0.1:12618 --http-alias=localhost:12618
    hostname: aosd
    ports:
      - 12618:12618
      - 6620:6620
    expose:
      - "12618"
    volumes:
      - aos-data-volume:/opt/arisen/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  awallet:
    image: arisen/arisen
    command: /opt/arisen/bin/awallet --wallet-dir /opt/arisen/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=awallet:8900 --http-alias=localhost:8900
    hostname: awallet
    links:
      - aosd
    volumes:
      - awallet-data-volume:/opt/arisen/bin/data-dir
    stop_grace_period: 10m

volumes:
  aos-data-volume:
    external: true
  awallet-data-volume:
    external: true
